name: Twitch.Js Test

on: [push,pull_request]

jobs:
  tester:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build Project
      run: npm run build
    - name: Run tests
      run: npm test
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
