name: Publish to NPM

on:
  workflow_run:
    workflows: ["Twitch.Js Test"]
    types: [completed]
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Setup .npmrc (NPM)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          scope: '@twitchapis'

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
