name: Publish to NPM

on:
  workflow_run:
    workflows: ["Twitch.Js Test"]
    types: [completed]
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: Setup .npmrc (NPM)
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          scope: '@twitchapis'
      - name: Update NPM
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Prepare package
        run: npm run pdeploy
      - name: Publish to npm
        working-directory: ./build
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
