name: Update Documentation

on:
  workflow_run:
    workflows: ["Publish to NPM"]
    types: [completed]
    branches: [release]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Generate Documentation
        run: npm run genDocs

      - name: Copy documentation into cache
        run: |
          mkdir -p docs
          cp -r out/html/* docs/

      - name: Create a Cache
        uses: actions/cache@v4
        with:
          path: ./docs
          key: docs-cache-${{ github.sha }}
          restore-keys: |
            docs-cache-
  
  publish:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: docs
      
      - name: Delete old documentation
        run: rm -rfv docs/*

      - name: Copy documentation from cache
        uses: actions/cache@v4
        with:
          path: ./docs
          key: docs-cache-${{ github.sha }}
          restore-keys: |
            docs-cache-
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: docs
          message: 'docs: Update documentation'
          committer_name: GitHub Actions
          committer_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
