name: Update Documentation

on:
  workflow_run:
    workflows: ["Twitch.Js Test"]
    types: [completed]
    branches: [release]

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Setup .npmrc (NPM)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          scope: '@twitchapis'

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Generate Documentation
        run: npm run genDocs

      - name: Create a Cache
        uses: actions/cache@v4
        with:
          path: ./docs
          key: ${{ runner.os }}-docs-cache-{{ github.sha }}
      
      - name: Copy documentation into cache
        run: cp out/html/* docs/
  
  publish:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: docs
      
      - name: Delete old documentation
        run: rm -rf docs/*

      - name: Copy documentation from cache
        uses: actions/cache@v4
        with:
          path: ./docs
          key: ${{ runner.os }}-docs-cache-{{ github.sha }}
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
          message: 'docs: Update documentation'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
